[project]
name = "ota-fl"
version = "0.1.0"
description = "Adaptive Federated Learning Over the Air - ST4001 Thesis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pypdf>=6.9.1",
    "scipy>=1.17.1",
    "setuptools<82.0.0",
    "tensorboard>=2.18.0",
    "tensorboardx>=2.6.2.2",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]
